FROM python:3.8.5-slim-buster

ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR /register
COPY . .

RUN pip install -r requirements.txt
RUN pip install gunicorn
RUN pip install google.cloud.firestore
RUN pip install firestore
RUN pip install firebase_admin

#Run the web service on container startup
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 120 register:app
